"""Thin generation wrappers for the tutor models used to build candidates.

Two backends, because the point of the candidate pool is *diversity* of tutor
behavior: a pool generated by one model family would give the grader an easy,
unrealistic job. MRBench itself mixes GPT-4, Llama, Gemini, Mistral, Phi and
Claude for the same reason.

  * `anthropic_generate` uses the official Anthropic SDK.
  * `openai_compatible_generate` covers OpenAI and any OpenAI-compatible
    endpoint (Together, Fireworks, a local vLLM server, ...).

Nothing here is used by the transfer experiments (c/d/e) -- only by
scripts/build_candidates.py.
"""

from __future__ import annotations

import os
from collections.abc import Callable
from dataclasses import dataclass

# Tutor persona shared by every generator, so that differences between the
# candidate responses come from the model rather than from the prompt.
TUTOR_SYSTEM_PROMPT = """You are an expert programming tutor helping a student \
who has written buggy code. You are having a live conversation with them.

Write ONE short tutor turn (1-3 sentences) in reply to the student's last message.
Do not write a preamble, a sign-off, or anything but the tutor's turn itself.

You may choose to point out the mistake, ask a question, give a hint, explain a \
concept, or give the student the corrected code -- respond the way you think a \
good tutor would. Do not follow a fixed template."""


@dataclass
class ModelSpec:
    """One tutor model in the candidate pool."""

    name: str  # short label stored as `tutor_name` on the record
    backend: str  # "anthropic" or "openai_compatible"
    model_id: str
    temperature: float = 1.0
    max_tokens: int = 1000


# The default pool. Three model families so the candidate responses differ in
# style, not just in sampling noise. Edit freely -- `--models` on the CLI
# selects a subset by name.
MODEL_REGISTRY: dict[str, ModelSpec] = {
    "claude-opus-5": ModelSpec("claude-opus-5", "anthropic", "claude-opus-5"),
    "claude-haiku-4-5": ModelSpec("claude-haiku-4-5", "anthropic", "claude-haiku-4-5"),
    "gpt-4o": ModelSpec("gpt-4o", "openai_compatible", "gpt-4o"),
    "gpt-4o-mini": ModelSpec("gpt-4o-mini", "openai_compatible", "gpt-4o-mini"),
}

_anthropic_client = None
_openai_clients: dict[str, object] = {}


def _get_anthropic_client():
    global _anthropic_client
    if _anthropic_client is None:
        import anthropic

        # Zero-arg constructor: resolves ANTHROPIC_API_KEY, ANTHROPIC_AUTH_TOKEN,
        # or an `ant auth login` profile.
        _anthropic_client = anthropic.Anthropic()
    return _anthropic_client


def _get_openai_client(base_url: str | None = None):
    key = base_url or "default"
    if key not in _openai_clients:
        from openai import OpenAI

        if base_url:
            _openai_clients[key] = OpenAI(
                base_url=base_url, api_key=os.environ.get("OPENAI_COMPAT_API_KEY")
            )
        else:
            _openai_clients[key] = OpenAI()
    return _openai_clients[key]


def anthropic_generate(spec: ModelSpec, prompt: str, system: str = TUTOR_SYSTEM_PROMPT) -> str:
    """Generate one tutor turn with the Anthropic API."""
    client = _get_anthropic_client()
    response = client.messages.create(
        model=spec.model_id,
        max_tokens=spec.max_tokens,
        # Stable across every call, so it is worth caching.
        system=[{"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": prompt}],
    )
    if response.stop_reason == "refusal":
        raise RuntimeError(
            f"{spec.name} refused to generate: "
            f"{getattr(response.stop_details, 'explanation', 'no explanation')}"
        )
    return "".join(b.text for b in response.content if b.type == "text").strip()


def openai_compatible_generate(
    spec: ModelSpec, prompt: str, system: str = TUTOR_SYSTEM_PROMPT
) -> str:
    """Generate one tutor turn with OpenAI or any OpenAI-compatible endpoint."""
    base_url = os.environ.get("OPENAI_COMPAT_BASE_URL") or None
    client = _get_openai_client(base_url)
    response = client.chat.completions.create(
        model=spec.model_id,
        max_tokens=spec.max_tokens,
        temperature=spec.temperature,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
    )
    return (response.choices[0].message.content or "").strip()


BACKENDS: dict[str, Callable[..., str]] = {
    "anthropic": anthropic_generate,
    "openai_compatible": openai_compatible_generate,
}


def generate_response(spec: ModelSpec, prompt: str, system: str = TUTOR_SYSTEM_PROMPT) -> str:
    """Dispatch to the right backend for a model spec."""
    if spec.backend not in BACKENDS:
        raise ValueError(f"unknown backend {spec.backend!r} for model {spec.name!r}")
    return BACKENDS[spec.backend](spec, prompt, system)


def build_tutor_prompt(dialogue_context: str) -> str:
    """The user-turn prompt: just the transcript so far."""
    return f"Here is the conversation so far.\n\n{dialogue_context}\n\nWrite the tutor's next turn."
